
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------
package uk.ac.ucl.jsh;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOUBLEQUOTECONTENT = 12;
  public static final int PIPE = 8;
  public static final int UNQUOTED = 10;
  public static final int WHITESPACE = 9;
  public static final int SEMI = 7;
  public static final int GREATER = 5;
  public static final int SINGLEQUOTE = 3;
  public static final int EOF = 0;
  public static final int LESS = 6;
  public static final int error = 1;
  public static final int DOUBLEQUOTE = 2;
  public static final int BACKQUOTE = 4;
  public static final int NON_NEWLINE_NON_SINGLE_QUOTE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOUBLEQUOTE",
  "SINGLEQUOTE",
  "BACKQUOTE",
  "GREATER",
  "LESS",
  "SEMI",
  "PIPE",
  "WHITESPACE",
  "UNQUOTED",
  "NON_NEWLINE_NON_SINGLE_QUOTE",
  "DOUBLEQUOTECONTENT"
  };
}

